In [79]:
# import Libraries
import pandas as pd
import random

In [80]:
# synthetic ecommerce dataset.

random.seed(42)

# Define data parameters
regions = ['North', 'South', 'East', 'West']
categories = ['Electronics', 'Clothing', 'Home & Garden', 'Sports', 'Books']
salespersons = ['Alice', 'Bob', 'Carol', 'David', 'Emma', 'Frank']

# Generate 200 sales transactions
data = {
    'transaction_id': range(1001, 1201),
    'region': [random.choice(regions) for _ in range(200)],
    'category': [random.choice(categories) for _ in range(200)],
    'salesperson': [random.choice(salespersons) for _ in range(200)],
    'sales_amount': [round(random.uniform(50, 5000), 2) for _ in range(200)],
    'customer_id': [random.randint(5000, 5100) for _ in range(200)]
}

df = pd.DataFrame(data)

print(df.head(10))
print("\nDataset shape:", df.shape)

   transaction_id region     category salesperson  sales_amount  customer_id
0            1001  North  Electronics        Emma       4000.80         5075
1            1002  North        Books       Alice       3634.70         5084
2            1003   East  Electronics       David       4210.50         5025
3            1004  South  Electronics        Emma       4601.73         5054
4            1005  South     Clothing         Bob       4904.57         5014
5            1006  South     Clothing       Carol       2693.91         5069
6            1007  North       Sports       Alice       4539.30         5028
7            1008  North       Sports       Frank       2979.87         5082
8            1009   West       Sports       David       3331.85         5019
9            1010  North     Clothing       Alice        465.54         5034

Dataset shape: (200, 6)

# Task 1: Basic Grouping and Single Aggregations

## 1.1 Total sales per region

In [81]:
# Identify which region generates the highest revenue.

region_sales = df.groupby('region')['sales_amount'].sum().reset_index()
(region_sales)

  region  sales_amount
0   East      95189.81
1  North     135181.16
2  South     158977.36
3   West     109383.07

## 1.2 Count Transactions Per Category

In [82]:
# Identify which product category sells most frequently
category_transactions = df.groupby('category')['transaction_id'].count().reset_index()

category_transactions

        category  transaction_id
0          Books              39
1       Clothing              42
2    Electronics              45
3  Home & Garden              43
4         Sports              31

## 1.3 Average Sales per Salesperson

In [83]:
# To analyze average sales value generated by each salesperson

avg_salesperson = df.groupby('salesperson')['sales_amount'].mean().reset_index()
avg_salesperson

  salesperson  sales_amount
0       Alice   1998.432273
1         Bob   2554.919063
2       Carol   2454.368571
3       David   2743.036444
4        Emma   2493.457273
5       Frank   2464.135750

## 1.4 Convert the Result into Clean DataFrame

In [84]:
# Convert into a Normal DataFrame  Column.
region_sales_sorted = region_sales.sort_values(by='sales_amount', ascending=False)

region_sales_sorted

  region  sales_amount
2  South     158977.36
1  North     135181.16
3   West     109383.07
0   East      95189.81

# Task 2: Multi-Column Grouping and Multiple Aggregations

## 2.1 Sales by Region AND Category

In [85]:
# TO identify which product category performs best in each region.

region_category_sales  = df.groupby(['region', 'category'])['sales_amount'].sum().reset_index()
region_category_sales

   region       category  sales_amount
0    East          Books      20027.53
1    East       Clothing      19926.20
2    East    Electronics      22791.55
3    East  Home & Garden      15949.08
4    East         Sports      16495.45
5   North          Books      42592.53
6   North       Clothing      18959.06
7   North    Electronics      38889.84
8   North  Home & Garden      19344.48
9   North         Sports      15395.25
10  South          Books      21007.68
11  South       Clothing      50878.36
12  South    Electronics      39229.63
13  South  Home & Garden      22592.00
14  South         Sports      25269.69
15   West          Books      20359.41
16   West       Clothing      16548.81
17   West    Electronics      13553.27
18   West  Home & Garden      33069.36
19   West         Sports      25852.22

## 2.2 Multiple Metrics Per Salesperson

In [86]:
## Calculate 3 metrics together:
# Total sales
# Average sales
# Number of transactions

region_category_sales = df.groupby(['region','category'])['sales_amount'].sum().reset_index()

region_category_sales

   region       category  sales_amount
0    East          Books      20027.53
1    East       Clothing      19926.20
2    East    Electronics      22791.55
3    East  Home & Garden      15949.08
4    East         Sports      16495.45
5   North          Books      42592.53
6   North       Clothing      18959.06
7   North    Electronics      38889.84
8   North  Home & Garden      19344.48
9   North         Sports      15395.25
10  South          Books      21007.68
11  South       Clothing      50878.36
12  South    Electronics      39229.63
13  South  Home & Garden      22592.00
14  South         Sports      25269.69
15   West          Books      20359.41
16   West       Clothing      16548.81
17   West    Electronics      13553.27
18   West  Home & Garden      33069.36
19   West         Sports      25852.22

# 2.3 Identify Top salesperson

In [87]:
# To identify best salesperson based on total revenue generated
top_salesperson = salesperson_metrics.sort_values(by='sum', ascending=False)
top_salesperson

  salesperson        sum         mean  count
3       David  123436.64  2743.036444     45
5       Frank   98565.43  2464.135750     40
4        Emma   82284.09  2493.457273     33
1         Bob   81757.41  2554.919063     32
2       Carol   68722.32  2454.368571     28
0       Alice   43965.51  1998.432273     22

# 2.4 Category with Maximum Total revenue

In [88]:
# To Identify Ctegory Generates highest Revenue
category_sales = df.groupby('category')['sales_amount'].sum()

top_category = category_sales.idxmax()

print("Top Revenue category:", top_category)

Top Revenue category: Electronics

# Task 3: Custom Aggregation and Complete Sales Report

## 3.1 Create Custom Aggregation Function

In [89]:
# Measure Sales variability with each region
def sales_range(x):
  return x.max()- x.min()

## 3.2 Apply Custom Funtion with Standard Aggregation

In [90]:
# Generate detailed statistical summary  per region
region_analysis = df.groupby('region')['sales_amount'].agg(['sum','mean','min','max',sales_range]).reset_index()
region_analysis

  region        sum         mean     min      max  sales_range
0   East   95189.81  2213.716512  307.82  4758.46      4450.64
1  North  135181.16  2413.949286  110.71  4788.56      4677.85
2  South  158977.36  2789.076491  373.45  4983.33      4609.88
3   West  109383.07  2485.978864  203.60  4903.53      4699.93

##3.3 Final Summary Report

In [92]:
# Complete Management Sales Report
final_report = df.groupby('region').agg({
    'sales_amount': ['sum','mean'],
    'customer_id': 'count'
}).reset_index()

final_report

  region sales_amount              customer_id
                  sum         mean       count
0   East     95189.81  2213.716512          43
1  North    135181.16  2413.949286          56
2  South    158977.36  2789.076491          57
3   West    109383.07  2485.978864          44

## 3.4 Multi-Level Column Explanation

In [95]:
# Dictionary aggregation creates hierarchical column names.

final_report.columns = ['region', 'total_sales', 'avg_sales', 'total_transactions']